theme: jekyll-theme-minimal
title: Indiana University Network Science Institute
description: Project Documentation

## IUNI Logo
logo: "index/favicon-194x194.png" # path of site logo, e.g. "/assets/images/logo.png"

